### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by acabal** [drgrigg/h-g-wells_the-history-of-mr-polly#1]
- I see for dialect words, the eliding right single quote is *outside*  the `<em>` tag. For example `“ ’<em>Ere’s</em> your ’at,”`. Can you move those single quotes inside the em tag, as they're part of the word? You can search for: `’<em>` to find candidates.
- Use "H. G. Wells" instead of full name in colophon
- In colophon, J.P. should be `<abbr class="initialism">JP</abbr>`

**Comment by drgrigg** [comment]
Done.
